# Запускается после main.yml, проверяет докер, собирает Image, проверяет, стартует контейнер  
---
- name: Ensure Docker is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Build Docker image
  community.docker.docker_image:
    name: "microservice:latest"
    build:
      path: "/opt/microservice"
    source: build
  register: image_build

- name: Create systemd service directory
  file:
    path: /etc/systemd/system
    state: directory
    mode: '0755'

- name: Deploy systemd service file
  template:
    src: "templates/microservice.service.j2"
    dest: "/etc/systemd/system/microservice.service"
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Ensure systemd daemon is reloaded
  systemd:
    daemon_reload: yes

- name: Enable and start microservice
  systemd:
    name: microservice
    state: started
    enabled: yes
